### ISSUE TITLE
Builds using .NET 6.0.x no longer work on the Windows Server 2019 image

### ISSUE THREAD

**Issue by simon-biber** [actions/virtual-environments#5522]
### Description

In May 2022, Microsoft released .NET 6.0.5 with SDK 6.0.300. [6.0.300 and newer SDKs require a minimum Visual Studio version of 17.0](https://docs.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs). Builds that use .NET 6.0.x no longer work on the Azure pipelines Windows Server 2019 image because it does not have Visual Studio 2022. The builds produce the error `Version 6.0.300 of the .NET SDK requires at least version 17.0.0 of MSBuild`.

Our pipelines are all set up with the `windows-2019` image and the `UseDotNet@2` task to ensure the SDK version `6.0.x` is available.

We can work around this by modifying all our pipelines to use the `windows-2022` Windows Server 2022 image, or to specify the exact .NET version 6.0.4. Pinning to .NET 6.0.4 is not desirable because it means we are using a version with known security issues  rather than the version with the latest security patches. Using Windows Server 2022 is a solution but risks introducing other unexpected changes to the build process.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: windows-2019
Version: 20220503.1

### Expected behavior

Expected to be able to continue using Windows Server 2019 to build .NET 6.0.x applications.

### Actual behavior

Builds fail with the error:
`D:\a\1\s\xxxx\xxxx\xxxx.csproj : error : Version 6.0.300 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.`

### Repro steps

Build a .NET project in an Azure pipeline with the `windows-2019` image and the `UseDotNet@2` task to ensure the SDK version `6.0.x` is installed:

```
  - job: Build
    pool:
      name: 'Azure Pipelines'
      vmImage: windows-2019
    steps:

    - task: UseDotNet@2
      displayName: 'Use .Net 6.0'
      inputs:
        packageType: 'sdk'
        version: '6.0.x'
```

**Comment by ph-ict** [comment]
We're getting this too.

**Comment by MaceWindu** [comment]
Another form of this issue (win-2022 BTW):
```cs
##[error]CSC(0,0): Error CS8032: An instance of analyzer Microsoft.CodeAnalysis.MakeFieldReadonly.MakeFieldReadonlyDiagnosticAnalyzer cannot be created from C:\hostedtoolcache\windows\dotnet\sdk\6.0.300\Sdks\Microsoft.NET.Sdk\codestyle\cs\Microsoft.CodeAnalysis.CodeStyle.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
```

https://dev.azure.com/linq2db/linq2db/_build/results?buildId=8566&view=logs&j=ebd22f9f-f810-563d-8875-507d3521ddec&t=97ce144a-eb37-5667-03d4-ea815c023f45

Fixing net 6 SDK to previous release 6.0.203 "resolves" it.

**Comment by igorboskovic3** [comment]
Hi @simon-biber, thank you for reporting this issue.

We will not install Visual Studio 2002 to win19 image, so I suppose you have two options:
-	use .Net 6.04
-	switch to windows2022

but before that let us see what  guys from .Net team think?

@timheuer  Can you take a look? 

Thank you

**Comment by simon-biber** [comment]
Is there a way via the 'use dotnet' task or another task to install whatever it needs (apparently msbuild 17) to run builds using the 6.0.5 SDK on the fly?

**Comment by igorboskovic3** [comment]
MSBuild is part of VS, so it is difficult to install MSBuild 17 on the fly

**Comment by timheuer** [comment]
@igorboskovic3 yes the recommended options (pin SDK or use latest agent) are correct. I’ll add a few more here that may be scenario dependent:

- if using .NET core-based projects just use `dotnet build` and other tasks (eg restore)
- If no windows dependencies, can also use `ubuntu-latest` image

**Comment by igorboskovic3** [comment]
@timheuer Thank you for this addition suggestions and clarification.

**Comment by jbrezina** [comment]
We cannot switch to the latest image with VS 2022 because App service does not support containers based on new Windows:
`##[error]Error: Failed to patch App Service configuration. Error: UnsupportedMediaType - The parameter WindowsFxVersion has an invalid value. Cannot run the specified image as a Windows Containers Web App. App Service supports Windows Containers up to Windows Server Core 2019 and Nanoserver 1809. Platform of the specified image: windows, Version: 10.0.20348.643; (CODE: 415)`
Why won't you install VS 2022 on the 2019 image? This forces users to use .NET with security issues.

**Comment by timheuer** [comment]
@jbrezina can you clarify this scenario for me? I'm confusing the error messages you are seeing...what is being built here (bonus if you have a pointer to the project). It sounds like you are building something with the Windows SDK correct?

**Comment by jbrezina** [comment]
We are building docker app based on Windows Server Core image which has to be built on the same OS as the host of the docker app. When we use the 2022 version, we get the above mentioned error in the App Service - it is not supported. I could not find any information about officialy supported host OSs or any roadmap mentioning support of new versions in App Service.

**Comment by timheuer** [comment]
@jbrezina Thank you for clarifying for me as it helped me understand the error you were seeing. I also don't know the App Service support OS roadmap especially since it does appear a 2022 LTSC release exists for server core: https://hub.docker.com/_/microsoft-windows-servercore

For your scenario, it sounds like the best option will be to pin to an SDK that works until a known resolution on the App Service side of moving to Server 2022.  I also couldn't find clear documentation on App Service and server versioning for container support -- I might log a support ticket with your Azure account to see if they can get you better information.

**Comment by jbrezina** [comment]
@timheuer Thank you for your help. It is the solution (stick to the latest working version of the SDK) we are using for now as there is no other way for now.
If you can create a ticket and help create better documentation in this regard it would be appreciated as we found out only because of the log error about the unsupported OS versions.

**Comment by FullStackPro** [comment]
Close VS and delete/rename global.json file and then reopen your project in VS and voila...

**Comment by MaceWindu** [comment]
@FullStackPro on CI?
