### ISSUE TITLE
Update Aure CLI because of bug in Version 2.28.0

### ISSUE THREAD

**Issue by SebastianSchuetze** [actions/virtual-environments#4275]
### Description

I hope it's enough to reference the original bug:

https://github.com/Azure/azure-cli/issues/19475

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

All releases that are released when writing this report (so all latest of them currently)

### Is it regression?

Yes. not sure but it worked fine with images that had Azure CLI 2.27.2 running

### Expected behavior

az container logs (or delete) works as expected with Azure CLI

### Actual behavior

az container logs (or delete) do not work using any image

### Repro steps

1. have an ACI somewhere running
2. Make a pipeline with the task:
```yaml
- task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: ${{ parameters.azureResourceManagerConnection }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az container delete --name ${{ parameters.containerName }} --resource-group ${{ parameters.resourceGroupName }} -y
```
3. See error like
```
/usr/bin/bash /home/vsts/work/_temp/azureclitaskscript1633914258266.sh
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: 'ContainerGroupsOperations' object has no attribute 'delete'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/container/custom.py", line 66, in delete_container
    return client.delete(resource_group_name, name)
AttributeError: 'ContainerGroupsOperations' object has no attribute 'delete'
To open an issue, please run: 'az feedback'
##[error]Script failed with exit code: 1

```

**Comment by rifaterdemsahin** [comment]
is this related to this one ?
https://github.com/MicrosoftDocs/azure-docs/issues/82665
