### ISSUE TITLE
Building using nmake on Azure Pipelines broke in windows-2022 image 20220710.1

### ISSUE THREAD

**Issue by swt2c** [actions/virtual-environments#5986]
### Description

Before image 20220710.1, it used to be possible to use nmake to build a VS project on windows-2022.  However, this no longer works as nmake doesn't seem to be able to find system headers:

```
nmake.exe -f makefile.vc UNICODE=1 OFFICIAL_BUILD=1 COMPILER_VERSION=140 SHARED=1 MONOLITHIC=0 USE_OPENGL=1 USE_GDIPLUS=1 BUILD=release

Microsoft (R) Program Maintenance Utility Version 14.32.31332.0
Copyright (C) Microsoft Corporation.  All rights reserved.

	if not exist vc140_mswudll mkdir vc140_mswudll
	if not exist ..\..\lib\vc140_dll mkdir ..\..\lib\vc140_dll
	if not exist ..\..\lib\vc140_dll\mswu mkdir ..\..\lib\vc140_dll\mswu
	if not exist ..\..\lib\vc140_dll\mswu\wx mkdir ..\..\lib\vc140_dll\mswu\wx
	if not exist ..\..\lib\vc140_dll\mswu\wx\setup.h copy ..\..\include\wx\msw\setup.h ..\..\lib\vc140_dll\mswu\wx\setup.h
        1 file(s) copied.
	if not exist ..\..\lib\vc140_dll\mswu\wx\msw mkdir ..\..\lib\vc140_dll\mswu\wx\msw
	cl /EP /nologo  "..\..\include\wx\msw\genrcdefs.h" > "..\..\lib\vc140_dll\mswu\wx\msw\rcdefs.h"
genrcdefs.h
	cl /c /nologo /TC /Fovc140_mswudll\wxregex_pcre2_auto_possess.obj /MD /DWIN32  /Zi /Fd..\..\lib\vc140_dll\wxregexu.pdb   /O2 /D_CRT_SECURE_NO_DEPRECATE=1  /D_CRT_NON_CONFORMING_SWPRINTFS=1 /D_SCL_SECURE_NO_WARNINGS=1  /D__NO_VC_CRTDBG__ /DTARGET_CPU_COMPFLAG=0 /DNDEBUG  /D_CRT_SECURE_NO_WARNINGS /I..\..\include /I..\..\lib\vc140_dll\mswu  /I..\..\3rdparty\pcre\src\wx /D__WX__ /DHAVE_CONFIG_H /D_UNICODE    ..\..\3rdparty\pcre\src\pcre2_auto_possess.c
pcre2_auto_possess.c
D:\a\1\s\ext\wxWidgets\include\wx/chartype.h(105): fatal error C1083: Cannot open include file: 'tchar.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.32.31326\bin\HostX86\x86\cl.EXE"' : return code '0x2'
Stop.
```

This worked fine with 20220626.1 (here's an example: https://alldunn.visualstudio.com/wxPython-CI/_build/results?buildId=965)

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220710.1

https://alldunn.visualstudio.com/wxPython-CI/_build/results?buildId=972

### Is it regression?

Yes 20220626.1 https://alldunn.visualstudio.com/wxPython-CI/_build/results?buildId=965

### Expected behavior

Build successfully.

### Actual behavior

Build fails.

### Repro steps

Run CI job.

**Comment by al-cheb** [comment]
Hey @swt2c.
We will take a look at it.

**Comment by al-cheb** [comment]
I was able to reproduce the issue. Looks like building tools can't find path to libs. I took [msvc-dev-cmd](https://github.com/ilammy/msvc-dev-cmd ) task to  initialize VS environment  and the build completed successfully. 

```
jobs:
  build:
    runs-on: windows-2022

    steps:
     - uses: actions/checkout@v3
       with:
        repository: 'wxWidgets/Phoenix'
        submodules: 'recursive'
     - uses: actions/setup-python@v4
       with:
        python-version: '3.10'        
     - name: Install dep
       run: |
          curl.exe -O https://bootstrap.pypa.io/get-pip.py
          python get-pip.py
          python -m pip install -U setuptools wheel
          python -m pip install -r requirements.txt
     - uses: ilammy/msvc-dev-cmd@v1
     - name: build
       run: |
          python build.py --jobs=4 build_wx
```

![image](https://user-images.githubusercontent.com/47745270/181711954-b258d0b9-acfb-4497-9abd-7ce0d144349c.png)

**Comment by swt2c** [comment]
Thanks @al-cheb - I can't use ilammy/msvc-dev-cmd on Azure Pipelines, though, can I?

**Comment by dmitry-shibanov** [comment]
Hello @swt2c. Could you please try to use this steps for windows-2022:
```yaml
- task: BatchScript@1
  displayName: 'Set up vcvarsall '
  inputs:
    filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat'
    arguments: x64
    modifyEnvironment: true
- script: |
   python build.py --jobs=4 build_wx
  displayName: 'Python build'
```

**Comment by swt2c** [comment]
@dmitry-shibanov, I can confirm that works.

**Comment by dmitry-shibanov** [comment]
Hello @swt2c. Thank you for your response. In this case I'm going to close the issue.

**Comment by MrMoose** [comment]
I came here having the same issue. Nmake can't be found. However, the proposed solution doesn't work for me. I already have the vcvarsall script called in all my jobs. Is this still visible?

**Comment by ruisantox** [comment]
I know the issue is close but I have the same problem. I notice nmake was/is not on the software listed https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md. It was available because other tool. It will be nmake available or not ? Tks

**Comment by ruisantox** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=msvc-170
