### ISSUE TITLE
MacOS Image 20211114.1 broke ICU (Unicode) support

### ISSUE THREAD

**Issue by dpaoliello** [actions/virtual-environments#4541]
### Description

Since the update to 20211114.1 we haven't been able to include the Unicode headers, they appear to be missing.

Note that we use CMake for the build, and in both cases CMake is able to find ICU:
```
-- Found the following ICU libraries:
--   core (required)
-- Found ICU: /usr/local/opt/icu4c/include (found version "69.1") 
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Virtual Environment
Environment: macos-11
Version: 20211114.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211114.1/images/macos/macos-11-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211114.1

### Is it regression?

Yes, 20211106.1 was working

### Expected behavior

Building against the Unicode include files works:
```
[  2%] Building CXX object CFlatCorlib/CMakeFiles/CFlatCorlib.dir/cmake_pch.hxx.pch
```

### Actual behavior

The unicode include files cannot be found:
```
[  2%] Building CXX object cmake_pch.hxx.pch
In file included from <built-in>:1:
In file included from cmake_pch.hxx:5:
In file included from /Users/runner/work/1/s/src/Os.h:75:
/Users/runner/work/1/s/src/Interop.ICU.h:27:10: fatal error: 'unicode/locid.h' file not found
#include <unicode/locid.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

### Repro steps

1. Add `/usr/local/opt/icu4c/include` to your include path.
2. Build a C++ file that includes `unicode/locid.h`

**Comment by dpaoliello** [comment]
Looks like the updates version of XCode now includes `unicode/utypes.h`, which was tripping our ICU detection logic:
```
Found unicode/utypes.h in /Applications/Xcode_13.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk/usr/include
```

Searching for `unicode/locid.h` fixed the issue.
