### ISSUE TITLE
node_modules/nativescript-ui-sidedrawer/references.d.ts:4:22 - error TS6053: File '/Users/bse/EMSA/med-mobile/Mobile/node_modules/nativescript-ui-sidedrawer/node_modules/nativescript-ui-core/android.d.ts' not found.

### ISSUE THREAD

**Issue by etelvinacunha** [actions/virtual-environments#2149]
**Description**  

After migrating the natiscript from 6.5.2 to 7 and after change the path on node_modules/nativescript-ui-sidedrawer/references.d.ts 

old path  /// <reference path="./node_modules/nativescript-ui-core/android.d.ts" />
 
new path  : /// <reference path="../nativescript-ui-core/android.d.ts" />

when we make clean and after build,  sometimes the changes are reverted to the old ones.
we can't reproduce this everytime , it's happens from time to time.

any help? any idea?

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Question
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ X] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by AlenaSviridenko** [comment]
Hi @etelvinacunha,
could you please provider minimal repro steps without `nativescript` module installed, so we can make sure the issue is related to the image and not to the node package which we do not own?
Thanks.

**Comment by etelvinacunha** [comment]
Hi @AlenaSviridenko , 

The buid and clean works with the older version of nativescript, after we migration to the new version, this behaviour start to begin.

**Comment by maxim-lobanov** [comment]
@etelvinacunha , In this repository, we manage pre-installed software on GitHub Actions Hosted images.
Since you mentioned that the issue is caused by version update of NativeScript NPM module, you should log this issue in repository related to this npm package, probably https://github.com/NativeScript. We are not affiliated with NativeScript npm package and don't own.

I am closing the issue now but please let me know if you have repro steps to proof that issue is related to GitHub Actions.
