### ISSUE TITLE
Windows Kernel Mode Build Broken with Latest Azure Pipelines

### ISSUE THREAD

**Issue by nibanks** [actions/virtual-environments#682]
**Describe the bug**
This morning it seems that Azure Pipelines took some kind of update because my teams' CI pipeline that builds our kernel mode code is completely broken.

[MSFT Internal Link Only]
https://microsoft.visualstudio.com/OS/_build/results?buildId=22662819&view=logs&j=1204e69e-9c52-5fc3-715c-177f7fdb0a3a&t=b2eebfab-7505-58e7-4497-5b1e11c53393&l=34

```
##[error]C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\km\ntddk.h(19206,1): Error C1001: Internal compiler error.
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\km\ntddk.h(19206,1): fatal error C1001: Internal compiler error. [d:\a\1\s\src\platform\platform.kernel.vcxproj]
  (compiler file 'msc1.cpp', line 1532)
   To work around this problem, try simplifying or changing the program near the locations listed above.
```

After some investigation, I was able to reproduce the build issue locally with VS version 16.5.1, but when I updated to 16.5.2 the issue was fixed. This is a very painful break for us, as this breaks our whole CI for a GitHub project. Would it be possible to update VS to the latest ASAP?

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**
Build succeeds.

**Actual behavior**
Build fails. See build link above (only accessible for MSFT).

**Comment by miketimofeev** [comment]
@nibanks could you try to add this workaround as the first step of your pipeline?
`Start-Process -Wait -FilePath  "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" -ArgumentList "update --passive --norestart --installpath ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"""`

**Comment by nibanks** [comment]
@miketimofeev that didn't seem to work:

https://microsoft.visualstudio.com/OS/_build/results?buildId=22821963&view=logs&j=1204e69e-9c52-5fc3-715c-177f7fdb0a3a&t=60496b87-ee54-57bc-2b15-3bd0b5dee969

The change I tried can be seen here:

https://github.com/microsoft/msquic/compare/nibanks/test-kernel-workaround?expand=1

**Comment by miketimofeev** [comment]
@nibanks Unfortunately, I don't have access to the logs, but it looks like you've made a mistake in the quotes, 
**you have**
`"update --passive --norestart --installpath 'C:\Program Files (x86)\Microsoft Visual **Studio\2019\Enterprise'"`
**should be**
`"update --passive --norestart --installpath ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"""`

Could you try with the proper quotes, please?

**Comment by nibanks** [comment]
That seemed to fix the builds. Thanks:

https://microsoft.visualstudio.com/OS/_build/results?buildId=22824684&view=logs&j=1204e69e-9c52-5fc3-715c-177f7fdb0a3a&t=1204e69e-9c52-5fc3-715c-177f7fdb0a3a

**Comment by nibanks** [comment]
Still awaiting deployment?! What's the ETA here?

**Comment by miketimofeev** [comment]
@nibanks the deployment was finished yesterday. Could you please check the VS version?

**Comment by nibanks** [comment]
Looks like the build succeeded without the workaround. Thanks.

**Comment by miketimofeev** [comment]
Closing the issue, but feel free to reopen if you have any concerns.
Thank you!
