### ISSUE TITLE
[macos] Missing cmath.h definitions

### ISSUE THREAD

**Issue by csparker247** [actions/virtual-environments#2274]
**Description**  
I've recently been getting build errors on a C++ project in the `macos-10.15` image. A compiler error is thrown because multiple things from `cmath.h` aren't found, like `::signbit`, `::isless`, and `::isgreater`. These are compiler errors from deep inside a dependency, in this case ITK, and not my code. 

```
In file included from /Users/runner/work/cpp-build-action/cpp-build-action/main.cpp:1:
In file included from /usr/local/include/ITK-5.1/itkMesh.h:32:
In file included from /usr/local/include/ITK-5.1/itkPointSet.h:32:
In file included from /usr/local/include/ITK-5.1/itkDefaultStaticMeshTraits.h:21:
In file included from /usr/local/include/ITK-5.1/itkCellInterface.h:24:
In file included from /usr/local/include/ITK-5.1/itkArray.h:24:
In file included from /usr/local/include/ITK-5.1/vnl/vnl_vector.h:23:
In file included from /usr/local/include/ITK-5.1/vnl/vnl_c_vector.h:24:
/Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace
using ::signbit;
```

I've seen this before on my personal machine, and it's almost always caused by something weird in the SDK configuration. My solution in those cases has been to make sure Xcode.app is uninstalled and only rely on the Command Line Tools. I first noticed this in Github Actions on 12/2/20 when [a job failed for a commit](https://github.com/viscenter/registration-toolkit/actions/runs/396682709), but then [another job succeeded on a tagged version of the same commit](https://github.com/viscenter/registration-toolkit/actions/runs/396699036). Prior to this, the job ran successfully. The timing implies that this has something to do with the change to a default Xcode 12.2.

I've setup a minimal project to explore the issue [here](https://github.com/csparker247/cpp-build-action). Thus far, I have observed the problem in both `macos-10.15` and `macos-11.0` when using the default Xcode. I do not have the problem on `macos-11.0` when I use:

 ```shell
sudo xcode-select -s "/Library/Developer/CommandLineTools/"
```

but this does not work on `macos-10.15`.  On that environment, I've tried using `Xcode_12.app`, `Xcode_12.1.1.app`, and `/Library/Developer/CommandLineTools/`, none of which work. I've also tried doing `export SDKROOT=[full SDK path]` along with `xcode-select`, since CMake pulls from that variable when determining the SDK to use.

I have already referred to https://github.com/actions/virtual-environments/issues/2056, https://github.com/actions/virtual-environments/issues/2211#issuecomment-739964760, and https://github.com/actions/virtual-environments/issues/2218 for possible solutions.

**Area for Triage**:  

Apple, C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Project builds successfully.

**Actual behavior**  
Compiler error due to missing definitions.

**Repro steps**  
I've setup a minimal example project [here](https://github.com/csparker247/cpp-build-action). It contains one action which performs all of the requisite steps. In brief, those steps are:

1. (optional) Set the Xcode version and/or SDKROOT
2. Run `brew install itk`
3. Setup a CMake executable project that includes `itkMesh.h` and links against `ITKCommon`
4. Try to compile.

**Comment by MaksimZhukov** [comment]
Hello @csparker247 !

We've reproduced this issue, but unfortunately we have not found the root cause yet. As a temporary solution you can define the `CPLUS_INCLUDE_PATH` environment variable for your entire workflow:
```
env:
  CPLUS_INCLUDE_PATH: /usr/local/opt/llvm/include/c++/v1:/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
```

We will continue to investigate the issue, I will keep you posted.

**Comment by MaksimZhukov** [comment]
Xcode Command Line Tools (12.2) installed on the `macOS-10.15` include both `MacOSX10.15.sdk` and `MacOSX11.0.sdk`. The `MacOSX.sdk` symlink points to the `MacOSX11.0.sdk`. Here is the output of the `ls -la /Library/Developer/CommandLineTools/SDKs` command:
```
total 0
drwxr-xr-x  5 root  wheel  160 Dec 12 21:15 .
drwxr-xr-x  5 root  wheel  160 Dec 12 21:14 ..
lrwxr-xr-x  1 root  wheel   14 Dec 12 21:15 MacOSX.sdk -> MacOSX11.0.sdk
drwxr-xr-x  8 root  wheel  256 Jul  9 16:33 MacOSX10.15.sdk
drwxr-xr-x  7 root  wheel  224 Oct 19 20:39 MacOSX11.0.sdk
 ```
 
To fix this issue you can override the `MacOSX.sdk` symlink and remove the `MacOSX11.0.sdk` from the `CommandLineTools/SDKs`:
```
- name: Override the MacOSX.sdk symLink
  run: |
    sudo rm /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
    sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk
    sudo ln -sf MacOSX10.15.sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk 
```

**Comment by csparker247** [comment]
Confirmed that this works on `macos-10.15` using CLT. I assume something similar would need to be done for those on 10.15 using Xcode_12.app. 

I am confused as to why this wouldn't work outright on `macos-11.0` by default. Assumably `MacOSX.sdk` in `Xcode_12.2.app` is symlinked to `MacOSX11.0.sdk`. 

Anyway, this hints to me that maybe there's something broken in CMake or ITK for resolving the correct SDK. If `MacOSX.sdk` is a moving target based on the tooling version, it seems like it should always try to find the SDK named `MacOSX10.15.sdk` if the target platform is 10.15.

**Comment by MaksimZhukov** [comment]
In this case, I am going to close this issue, but feel free to contact us if you have any concerns!
